### PR TITLE
Need to stop Sendmail

### PR DESCRIPTION
**Pull request by hyperknot**
Need to stop Sendmail, if not, it can screw up the exim4 installation, as the apt-get command doesn't shut down sendmail and sendmail keeps running and binding to port 25 and exim4 can go crazy.

### CODE REVIEW

**Comment by maxexcloo** [comment]
I will do this properly later.

**Comment by shaunpud** [comment]
# invoke-rc.d sendmail stop

**Comment by hyperknot** [comment]
Shaun, daemon_manage sendmail stop is the one line we need. I don't know how could it be more properly, I think my solution is elegant. It only doesn't check if Sendmail is going to be removed or not, but since it's clean packages, it will.

**Comment by maxexcloo** [comment]
Added in latest source, thanks for the report!

**Pull request closed without merging**
